### ISSUE TITLE
meh, remove this repo/npm package

### ISSUE THREAD

**Issue by jimmywarting** [standardjavascript/standardjs#2]

**Comment by waynebloss** [comment]
No.

**Comment by jimmywarting** [comment]
why not?

**Comment by waynebloss** [comment]
I choose not to.

**Comment by jimmywarting** [comment]
Not a answer, why do you choose not to?
what to you get out of it?

**Comment by waynebloss** [comment]
> Not a answer, ...

Oh, well perhaps that's because I don't have to answer to you :)
